# This is persistent storage for NFS clients to use.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $PV_NAME
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: $PV_NFS_SERVER
    path: $PV_NFS_PATH
  storageClassName: $STORAGECLASS_NAME

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: $PVC_NAME
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: $STORAGECLASS_NAME
  resources:
    requests:
      storage: 10Gi
