apiVersion: v1
kind: Service
metadata:
  name: nginx-revproxy
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.IP }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  {{- if .Values.SSL }}
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  {{- end }}
  selector:
    app: nginx-revproxy
