apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-revproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-revproxy
  template:
    metadata:
      labels:
        app: nginx-revproxy
    spec:
      containers:
      - image: heliumdatastage/nginx:bdcat-nginx-amb-2
        imagePullPolicy: Always
        name: ambassador-nginx-conf
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ambassador-nginx-conf
          mountPath: /etc/nginx/conf.d
      # Load the configuration files for nginx
      volumes:
        - name: ambassador-nginx-conf
          configMap:
            name: ambassador-nginx-conf
