kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elk-sc
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-elasticsearch
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: elk-sc
