apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $PVC_NAME
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: $PVC_STORAGE_CLASS_NAME
  resources:
    requests:
      storage: $PVC_STORAGE_REQUESTED
