apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $PVC_NAME
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: $PVC_STORAGE_REQUESTED
  storageClassName: $PVC_STORAGE_CLASS_NAME
