{{- if .Values.config.storageClass }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.config.claimName }}
  labels:
    {{- include "nfsrods.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: {{ .Values.config.storageClass }}
{{- end }}
