apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio-deployment #Name of the deployment.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio-demo #To later reference this deployment.
  template:
    metadata: #Information about the application
      labels:
        app: rstudio-demo
    spec:
      hostPID: true
      securityContext:
        runAsGroup: 1005
        fsGroup: 1004
      containers:
      - name: rstudio-demo
        image: "muralikarthikk/rstudio-demo:v3"
        imagePullPolicy: Always
        ports:
        - containerPort: 80 #Exposing port 80 on the R Studio container
        env:
        - name: PASSWORD
          value: "renci2019$"
        command: ["/bin/bash", "-c"]
        args: ["apt-get update && \
                python /user_mgmt.py && \
                chmod 770 /shareddata && \
                service auditd restart && \
                service filebeat restart && \
                /init"]
        volumeMounts:
          - name: rstudio-storage
            mountPath: /shareddata
            readOnly: false
          - name: config
            mountPath: /data/templates
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
      volumes:
        - name: rstudio-storage
          persistentVolumeClaim:
            claimName: pvc-for-rstudio
        - name: config
          configMap:
            name: rstudio-configmap        
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-rstudio
  annotations:
    pv.beta.kubernetes.io/gid: "1004"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: rstudio-disk-1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-rstudio
  labels:
    app: rstudio-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
